### ISSUE TITLE
2. Media library not showing up on intranet

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-intranet-theme#27] opened 2020-11-18 20:25 UTC
Also on our intranet (intranet.1.jccmi.edu) the media library isn't showing up, it's just a blank gray page.

**Comment by d4mation** [comment] 2020-11-24 13:44
This is now fixed :+1: It was caused by a plugin installed by the other developers as part of their development workflow throwing an error. Since it is no longer needed, I removed it.

**Closed by d4mation** 2020-11-24 13:44 UTC
Labels: bug
